services:
  e2e:
    build: .
    image: bootcamp/ext-e2e:latest
    environment:
      - CI=true
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm test
    shm_size: 2gb